version: '2'
services:
  python-api:
    build: ./python
    image: registry.alcachofa.faith/live/consequences/python-api:dev
    volumes:
      - ./python/:/app
      - ./data/:/data
    ports:
      - 8998:8000
    expose:
      - 8000
    environment:
      - EXAMPLE=value
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="/app/src" python /app/main.py
  nginx:
    build: ./web
    image: registry.alcachofa.faith/develop/live/nginx:dev
    volumes:
      - ./web/app/:/app
    ports:
      - 8491:80
